blank_issues_enabled: false
contact_links:
  - name: ¿Alguna pregunta?
    url: https://discord.com/channels/594363964499165194/1109220285841944586
    about: Consultanos lo que quieras en nuestro canal de Discord.
